### ISSUE TITLE
not marked as client side mod

### ISSUE THREAD

**Issue by Molier** [yungnickyoung/YUNGs-Menu-Tweaks#8]
using [itzg-docker](https://github.com/itzg/docker-minecraft-server/blob/master/examples/bmc4/docker-compose.yml) this causes crash since it wants to install on server using curseforge installer.
```Forge: net.minecraftforge:47.3.3[13:38:40] [main/ERROR] [minecraft/Main]: Failed to start the minecraft server
mcserv  | net.minecraftforge.fml.LoadingFailedException: Loading errors encountered: [
mcserv  |       YUNG's Menu Tweaks (yungsmenutweaks) has failed to load correctly
mcserv  | §7java.util.ServiceConfigurationError: com.yungnickyoung.minecraft.yungsmenutweaks.services.IPlatformHelper: com.yungnickyoung.minecraft.yungsmenutweaks.services.ForgePlatformHelper Unable to get public no-arg constructor
mcserv  | ]
mcserv  |       at net.minecraftforge.fml.ModLoader.waitForTransition(ModLoader.java:246) ~[fmlcore-1.20.1-47.3.3.jar%23740!/:?] {}
mcserv  |       at net.minecraftforge.fml.ModLoader.lambda$dispatchAndHandleError$20(ModLoader.java:210) ~[fmlcore-1.20.1-47.3.3.jar%23740!/:?] {}
mcserv  |       at java.util.Optional.ifPresent(Unknown Source) ~[?:?] {re:mixin}
mcserv  |       at net.minecraftforge.fml.ModLoader.dispatchAndHandleError(ModLoader.java:210) ~[fmlcore-1.20.1-47.3.3.jar%23740!/:?] {}
mcserv  |       at net.minecraftforge.fml.ModLoader.lambda$gatherAndInitializeMods$13(ModLoader.java:183) ~[fmlcore-1.20.1-47.3.3.jar%23740!/:?] {}
mcserv  |       at java.lang.Iterable.forEach(Unknown Source) ~[?:?] {re:mixin}
mcserv  |       at net.minecraftforge.fml.ModLoader.gatherAndInitializeMods(ModLoader.java:183) ~[fmlcore-1.20.1-47.3.3.jar%23740!/:?] {}
mcserv  |       at net.minecraftforge.server.loading.ServerModLoader.load(ServerModLoader.java:30) ~[forge-1.20.1-47.3.3-universal.jar%23744!/:?] {re:classloading}
mcserv  |       at net.minecraft.server.Main.main(Main.java:125) ~[server-1.20.1-20230612.114412-srg.jar%23739!/:?] {re:mixin,pl:connector_pre_launch:A,re:classloading,re:mixin,pl:connector_pre_launch:A,pl:mixin:A,pl:connector_pre_launch:A}
mcserv  |       at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source) ~[?:?] {}
mcserv  |       at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?] {}
mcserv  |       at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111) ~[fmlloader-1.20.1-47.3.3.jar%2369!/:?] {}
mcserv  |       at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.serverService(CommonLaunchHandler.java:103) ~[fmlloader-1.20.1-47.3.3.jar%2369!/:?] {}
mcserv  |       at net.minecraftforge.fml.loading.targets.CommonServerLaunchHandler.lambda$makeService$0(CommonServerLaunchHandler.java:27) ~[fmlloader-1.20.1-47.3.3.jar%2369!/:?] {}
mcserv  |       at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar%2355!/:?] {}
mcserv  |       at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar%2355!/:?] {}
mcserv  |       at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar%2355!/:?] {}
mcserv  |       at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar%2355!/:?] {}
mcserv  |       at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar%2355!/:?] {}
mcserv  |       at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar%2355!/:?] {}
mcserv  |       at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar%2355!/:?] {}
mcserv  |       at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?] {}
mcserv  | 2024/08/05 13:41:58 Stopping with rcon-cli```

docker compose as used:

```
```
 mc:
    image: itzg/minecraft-server
    container_name: mcserv
    labels:
      # Set lazymc.enabled to true to enable lazymc on this container
      - lazymc.enabled=true
      # Required to find the container to manage it
      - lazymc.group=mc
      # Point to the service name of the Minecraft server
      - lazymc.server.address=mc:25565
      - lazymc.server.forge=true
    tty: true
    stdin_open: true
    # This container should be managed solely by the lazymc container
    # so set restart to no, or else the container will start again...
    restart: no
    environment:
      EULA: true
      MOD_PLATFORM: AUTO_CURSEFORGE
      # Set CF_API_KEY=... in a .env file next to this compose file and don't source control that file
      CF_API_KEY: ${CF_API_KEY}
      CF_SLUG: better-mc-forge-bmc4
#      CF_FILENAME_MATCHER
      CF_FORCE_SYNCHRONIZE: "true"
      CF_EXCLUDE_MODS: |
          xaeros-minimap
          xaeroplus
          **# following line fixes the issue
          yungs-menu-tweaks**
      MEMORY: 8G
    volumes:
      - data:/data
      
      
```
